version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  dock_dj:
    build:
      context: ./dock_dj
    volumes:
      - ./dock_dj/:/app
      - static_volume:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DEBUG: "False"
      DB_NAME: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_HOST: "postgres"
      DB_PORT: 5432

  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    ports:
      - "80:80"
    depends_on:
      - dock_dj

volumes:
  pg_data:
  static_volume: